"""Conservative project initialization for the public CLI."""

from __future__ import annotations

import re
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from graphabi.adapters.detection import ADAPTER_PROJECT_HINTS, AdapterProjectHint

STARTER_CONTRACT = """# Example contract generated by `graphabi init`.
# Replace every placeholder with reviewed consumer requirements before comparison.
# This file is not inferred and is never enforced unless you pass it to GraphABI explicitly.
# Field guide:
# - nodes and graph_edges describe reviewed topology.
# - edges is the contracted subset whose consumer assumptions GraphABI should test.
# - destination_path/output paths must match values your instrumentation records.
version: "0.2"
graph: replace_with_graph_id
nodes:
  - id: producer
  - id: consumer
    terminal: true
graph_edges:
  - id: producer_to_consumer
    producer: producer
    consumer: consumer
edges:
  - id: producer_to_consumer
    producer: producer
    consumer: consumer
    invariants:
      - id: required_value_non_empty
        evaluator: completeness
        description: The consumer requires a non-empty value.
        severity: breaking
        destination_path: output.value
"""

RUNTIME_GITIGNORE = """# Local GraphABI runtime data
*.db
*.db-*
imports/
reports/
traces/
suggestions*.yml
"""

_DISTRIBUTION = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9_.-]*)")


class InitError(ValueError):
    """An actionable project-initialization failure."""


@dataclass(frozen=True)
class ProjectDetection:
    """Manifest-only project hints, never inferred graph topology."""

    project_name: str
    adapters: tuple[AdapterProjectHint, ...]
    evidence: tuple[str, ...]
    warnings: tuple[str, ...]


@dataclass(frozen=True)
class InitResult:
    """Files and next steps produced by one initialization."""

    project_root: Path
    created: tuple[str, ...]
    replaced: tuple[str, ...]
    detection: ProjectDetection
    next_commands: tuple[str, ...]


def detect_project_context(project_root: Path) -> ProjectDetection:
    """Detect maintained adapters from root dependency manifests only."""
    project_name = project_root.name or "graphabi-project"
    found_project_name = False
    distributions: dict[str, set[str]] = {}
    warnings: list[str] = []
    pyproject = project_root / "pyproject.toml"
    if pyproject.is_file():
        try:
            document = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, tomllib.TOMLDecodeError) as exc:
            warnings.append(f"pyproject.toml could not be read: {exc}")
        else:
            project = document.get("project")
            if isinstance(project, dict):
                declared_name = project.get("name")
                if isinstance(declared_name, str) and declared_name.strip():
                    project_name = declared_name.strip()
                    found_project_name = True
                _collect_requirement_list(
                    project.get("dependencies"),
                    "pyproject.toml project.dependencies",
                    distributions,
                )
                optional = project.get("optional-dependencies")
                if isinstance(optional, dict):
                    for group, values in optional.items():
                        _collect_requirement_list(
                            values,
                            f"pyproject.toml project.optional-dependencies.{group}",
                            distributions,
                        )
            groups = document.get("dependency-groups")
            if isinstance(groups, dict):
                for group, values in groups.items():
                    _collect_requirement_list(
                        values,
                        f"pyproject.toml dependency-groups.{group}",
                        distributions,
                    )
            if not found_project_name:
                poetry_name = _poetry_project_name(document)
                if poetry_name is not None:
                    project_name = poetry_name
            _collect_poetry_dependencies(document, distributions)

    for requirements in sorted(project_root.glob("requirements*.txt")):
        if not requirements.is_file():
            continue
        try:
            lines = requirements.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as exc:
            warnings.append(f"{requirements.name} could not be read: {exc}")
            continue
        for line in lines:
            stripped = line.strip()
            if not stripped or stripped.startswith(("#", "-")):
                continue
            _collect_requirement(stripped, requirements.name, distributions)

    adapters: list[AdapterProjectHint] = []
    evidence: list[str] = []
    for hint in ADAPTER_PROJECT_HINTS:
        matches = [
            (distribution, origin)
            for distribution in hint.distributions
            for origin in sorted(distributions.get(_normalize_distribution(distribution), set()))
        ]
        if not matches:
            continue
        adapters.append(hint)
        evidence.extend(f"{origin} declares {distribution!r}" for distribution, origin in matches)
    return ProjectDetection(
        project_name=project_name,
        adapters=tuple(adapters),
        evidence=tuple(evidence),
        warnings=tuple(warnings),
    )


def initialize_project(project_root: Path, *, force: bool = False) -> InitResult:
    """Create starter files without discovering topology or enabling contracts."""
    if not project_root.exists():
        raise InitError(f"project directory {project_root} does not exist; create it first")
    if not project_root.is_dir():
        raise InitError(f"project path {project_root} is not a directory; choose a directory")

    detection = detect_project_context(project_root)
    state_directory = project_root / ".graphabi"
    targets = {
        ".graphabi/config.yml": _render_config(detection),
        ".graphabi/contracts.yml": STARTER_CONTRACT,
        ".graphabi/README.md": _render_readme(detection),
        ".graphabi/.gitignore": RUNTIME_GITIGNORE,
    }
    if state_directory.is_symlink():
        raise InitError(
            f"state directory {state_directory} is a symbolic link; replace it with a local "
            "directory before initialization"
        )
    if state_directory.exists() and not state_directory.is_dir():
        raise InitError(
            f"state path {state_directory} is not a directory; move it before initialization"
        )
    for relative in targets:
        target = project_root / relative
        if target.is_symlink():
            raise InitError(
                f"starter path {target} is a symbolic link; replace it with a local file before "
                "initialization"
            )
        if target.exists() and not target.is_file():
            raise InitError(f"starter path {target} is not a file; move it before initialization")
    existing = tuple(relative for relative in targets if (project_root / relative).exists())
    if existing and not force:
        joined = ", ".join(existing)
        raise InitError(
            f"starter file(s) already exist: {joined}; review them or pass --force to replace "
            "only these generated starter files"
        )
    try:
        state_directory.mkdir(parents=True, exist_ok=True)
        for relative, content in targets.items():
            (project_root / relative).write_text(content, encoding="utf-8")
    except OSError as exc:
        raise InitError(f"could not initialize {state_directory}: {exc}") from exc

    next_commands = (
        "graphabi doctor",
        "graphabi check .graphabi/contracts.yml",
        "graphabi record path/to/baseline.json --database .graphabi/traces.db",
        "graphabi record path/to/candidate.json --database .graphabi/traces.db",
        (
            "graphabi compare --baseline-run BASELINE_RUN_ID --candidate-run CANDIDATE_RUN_ID "
            "--contract .graphabi/contracts.yml --database .graphabi/traces.db"
        ),
    )
    return InitResult(
        project_root=project_root,
        created=tuple(relative for relative in targets if relative not in existing),
        replaced=existing,
        detection=detection,
        next_commands=next_commands,
    )


def _render_config(detection: ProjectDetection) -> str:
    data = {
        "version": "0.1",
        "project": {
            "name": detection.project_name,
            "detected_adapters": [hint.adapter for hint in detection.adapters],
            "detection_evidence": list(detection.evidence),
            "detection_warnings": list(detection.warnings),
        },
        "graph": {
            "discovery": "NOT_ATTEMPTED",
            "reason": "Graph topology and consumer requirements require explicit review.",
        },
        "paths": {
            "contract": ".graphabi/contracts.yml",
            "trace_database": ".graphabi/traces.db",
            "reports": ".graphabi/reports",
        },
        "contract_policy": {
            "starter_status": "EXAMPLE_NOT_ENFORCED",
            "inference_status": "SUGGESTED_NOT_ENFORCED",
            "auto_enforce_inferred_contracts": False,
        },
    }
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=False)


def _render_readme(detection: ProjectDetection) -> str:
    if detection.adapters:
        adapter_names = ", ".join(f"`{hint.adapter}`" for hint in detection.adapters)
        evidence = "\n".join(f"- {item}" for item in detection.evidence)
        recording = "\n".join(
            f"- `{hint.adapter}`: {hint.recording_guidance} See {hint.documentation}."
            for hint in detection.adapters
        )
    else:
        adapter_names = "none"
        evidence = "- No maintained adapter dependency was found in a supported manifest."
        recording = (
            "- Emit a framework-independent `TraceBundle` 0.2, or import supported local "
            "OTLP/JSON with `graphabi import-otel`."
        )
    warnings = ""
    if detection.warnings:
        warning_lines = "\n".join(f"- {item}" for item in detection.warnings)
        warnings = f"\nDetection warnings:\n\n{warning_lines}\n"
    return f"""# GraphABI project state

`graphabi init` detected adapter context: {adapter_names}.

Detection is advisory and based only on dependency manifests. It does not prove that an adapter is
used, discover graph topology, infer consumer requirements, or enable enforcement.

Detection evidence:

{evidence}
{warnings}
## First debugging command

Run `graphabi doctor` before recording traces. It separates required runtime checks, optional
adapter availability, local config, trace-store state, contract parsing, and report artifacts.

## Record traces

{recording}

An adapter returns a framework-independent `TraceBundle`. Export it locally, then import it:

```python
from pathlib import Path

from graphabi.traces import export_json

export_json(bundle, Path(".graphabi/traces/baseline.json"))
```

```bash
graphabi record .graphabi/traces/baseline.json --database .graphabi/traces.db
```

## Review the sample contract

`.graphabi/contracts.yml` is an example, not an inferred or enforced contract. Replace its graph,
node, edge, and invariant placeholders with reviewed consumer requirements. Validate it explicitly:

```bash
graphabi check .graphabi/contracts.yml
```

`graphabi infer` emits `SUGGESTED: NOT ENFORCED` candidates. It never changes this contract file.

## Compare two recorded runs

```bash
graphabi compare \\
  --baseline-run BASELINE_RUN_ID \\
  --candidate-run CANDIDATE_RUN_ID \\
  --contract .graphabi/contracts.yml \\
  --database .graphabi/traces.db
```

`UNKNOWN` and `INSUFFICIENT_EVIDENCE` are not compatibility passes. Contract coverage is not
correctness.

More onboarding:

- https://github.com/graphabi/graphabi/blob/main/docs/quickstart.md
- https://github.com/graphabi/graphabi/blob/main/docs/langgraph-quickstart.md
- https://github.com/graphabi/graphabi/blob/main/docs/openai-agents-quickstart.md
- https://github.com/graphabi/graphabi/blob/main/docs/unknown.md
"""


def _collect_requirement_list(
    values: object,
    origin: str,
    distributions: dict[str, set[str]],
) -> None:
    if not isinstance(values, list):
        return
    for value in values:
        if isinstance(value, str):
            _collect_requirement(value, origin, distributions)


def _collect_poetry_dependencies(
    document: dict[str, Any], distributions: dict[str, set[str]]
) -> None:
    tool = document.get("tool")
    if not isinstance(tool, dict):
        return
    poetry = tool.get("poetry")
    if not isinstance(poetry, dict):
        return
    dependencies = poetry.get("dependencies")
    if isinstance(dependencies, dict):
        for name in dependencies:
            _collect_distribution_name(
                str(name), "pyproject.toml tool.poetry.dependencies", distributions
            )
    groups = poetry.get("group")
    if not isinstance(groups, dict):
        return
    for group, settings in groups.items():
        if not isinstance(settings, dict):
            continue
        grouped = settings.get("dependencies")
        if isinstance(grouped, dict):
            for name in grouped:
                _collect_distribution_name(
                    str(name),
                    f"pyproject.toml tool.poetry.group.{group}.dependencies",
                    distributions,
                )


def _poetry_project_name(document: dict[str, Any]) -> str | None:
    tool = document.get("tool")
    if not isinstance(tool, dict):
        return None
    poetry = tool.get("poetry")
    if not isinstance(poetry, dict):
        return None
    name = poetry.get("name")
    return name.strip() if isinstance(name, str) and name.strip() else None


def _collect_requirement(
    requirement: str,
    origin: str,
    distributions: dict[str, set[str]],
) -> None:
    match = _DISTRIBUTION.match(requirement)
    if match is not None:
        _collect_distribution_name(match.group(1), origin, distributions)


def _collect_distribution_name(
    name: str,
    origin: str,
    distributions: dict[str, set[str]],
) -> None:
    distributions.setdefault(_normalize_distribution(name), set()).add(origin)


def _normalize_distribution(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()
